package pomodoroplus;

import java.awt.Image;
import java.awt.Toolkit;

/**
 * Janela para carregar um programa.
 * @author Guilherme
 */
public class Carregar extends javax.swing.JDialog{

    Programa programa;
    
    /**
     * Creates new form Salvar
     * @param programa Referência para o objeto programa.
     */
    public Carregar(java.awt.Frame parent, boolean modal, Programa programa){
        super(parent, modal);
        this.programa = programa;
        initComponents();
        Image iconeTitulo = Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Figuras/icone.png"));
        this.setIconImage(iconeTitulo);
        
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelFundo = new javax.swing.JPanel();
        painelCabecalho = new javax.swing.JPanel();
        simboloProg = new javax.swing.JLabel();
        salvarLabel = new javax.swing.JLabel();
        botaoAbrir = new javax.swing.JButton();
        nomeLabel = new javax.swing.JLabel();
        escolha = new javax.swing.JComboBox();
        botaoExcluir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        painelFundo.setBackground(new java.awt.Color(238, 241, 246));

        painelCabecalho.setBackground(new java.awt.Color(255, 255, 255));

        simboloProg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Figuras/Tomate.png"))); // NOI18N

        salvarLabel.setFont(new java.awt.Font("Verdana", 1, 30)); // NOI18N
        salvarLabel.setText("Carregar");

        javax.swing.GroupLayout painelCabecalhoLayout = new javax.swing.GroupLayout(painelCabecalho);
        painelCabecalho.setLayout(painelCabecalhoLayout);
        painelCabecalhoLayout.setHorizontalGroup(
            painelCabecalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelCabecalhoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(simboloProg)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(salvarLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        painelCabecalhoLayout.setVerticalGroup(
            painelCabecalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelCabecalhoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(painelCabecalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(simboloProg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(salvarLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        botaoAbrir.setBackground(new java.awt.Color(255, 55, 45));
        botaoAbrir.setFont(new java.awt.Font("Verdana", 1, 20)); // NOI18N
        botaoAbrir.setForeground(new java.awt.Color(255, 255, 255));
        botaoAbrir.setText("Abrir");
        botaoAbrir.setBorderPainted(false);
        botaoAbrir.setFocusPainted(false);
        botaoAbrir.setPreferredSize(new java.awt.Dimension(101, 34));
        botaoAbrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoAbrirActionPerformed(evt);
            }
        });

        nomeLabel.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        nomeLabel.setText("Nome:");

        escolha.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        escolha.setModel(new javax.swing.DefaultComboBoxModel(programa.listarSalvos()));
        escolha.setMaximumRowCount(10);
        escolha.setMaximumSize(new java.awt.Dimension(378, 29));
        escolha.setMinimumSize(new java.awt.Dimension(378, 29));
        escolha.setPreferredSize(new java.awt.Dimension(378, 29));
        if(escolha.getItemCount()==0){
            escolha.setEnabled(false);
            botaoAbrir.setEnabled(false);
            botaoExcluir.setEnabled(false);
            escolha.setModel(new javax.swing.DefaultComboBoxModel(new String[]{"Não há programas salvos."}));
        }

        botaoExcluir.setBackground(new java.awt.Color(255, 55, 45));
        botaoExcluir.setFont(new java.awt.Font("Verdana", 1, 20)); // NOI18N
        botaoExcluir.setForeground(new java.awt.Color(255, 255, 255));
        botaoExcluir.setText("Excluir");
        botaoExcluir.setBorderPainted(false);
        botaoExcluir.setFocusPainted(false);
        botaoExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoExcluirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout painelFundoLayout = new javax.swing.GroupLayout(painelFundo);
        painelFundo.setLayout(painelFundoLayout);
        painelFundoLayout.setHorizontalGroup(
            painelFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelCabecalho, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(painelFundoLayout.createSequentialGroup()
                .addGroup(painelFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelFundoLayout.createSequentialGroup()
                        .addGroup(painelFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(painelFundoLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(nomeLabel))
                            .addGroup(painelFundoLayout.createSequentialGroup()
                                .addGap(61, 61, 61)
                                .addComponent(botaoAbrir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(67, 67, 67)
                                .addComponent(botaoExcluir)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(painelFundoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(escolha, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        painelFundoLayout.setVerticalGroup(
            painelFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelFundoLayout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(painelCabecalho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(nomeLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(escolha, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addGroup(painelFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoAbrir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoExcluir))
                .addContainerGap())
        );

        botaoAbrir.setUI(new UIBotao());
        botaoAbrir.setUI(new UIBotao());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelFundo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelFundo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoAbrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoAbrirActionPerformed
        programa.abreArquivo((String)escolha.getSelectedItem());
        this.dispose();
    }//GEN-LAST:event_botaoAbrirActionPerformed

    private void botaoExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoExcluirActionPerformed
        programa.excluir((String)escolha.getSelectedItem());
        escolha.setModel(new javax.swing.DefaultComboBoxModel(programa.listarSalvos()));
        if(escolha.getItemCount()==0){
            this.dispose();
        }
    }//GEN-LAST:event_botaoExcluirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoAbrir;
    private javax.swing.JButton botaoExcluir;
    private javax.swing.JComboBox escolha;
    private javax.swing.JLabel nomeLabel;
    private javax.swing.JPanel painelCabecalho;
    private javax.swing.JPanel painelFundo;
    private javax.swing.JLabel salvarLabel;
    private javax.swing.JLabel simboloProg;
    // End of variables declaration//GEN-END:variables
}