package pomodoroplus;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.text.ParseException;
import javax.swing.ImageIcon;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.text.MaskFormatter;

/**
 * Painel para a configuração de um período de tempo.
 * @author Guilherme
 */
public class Painel extends javax.swing.JPanel{

    //Janela que contêm os paineis
    private JPanel janela;
    //Barra de rolagem de janela
    private JScrollPane rolagem;
    //Janela principal do pragrama
    private JanelaPrincipal janelaPric;
    //Indica se o usuário escolheu um nome para o período
    private boolean nomePeriodoUsado = false;
    //Indica se o painel já foi incluído (Botão +)
    private boolean incluido = false;
    //Classe que representa o período de tempo
    Periodo periodo;
    //Ponteiro para o Programa do qual esse período fará parte
    Programa programa;
    
    boolean pronto = false;
    
    /**
     * Cria uma instância de Painel
     * @param janela Janela que contêm os paineis
     * @param rolagem Barra de rolagem de janela
     * @param janelaPric Janela principal do programa
     */
    public Painel(JPanel janela, JScrollPane rolagem, JanelaPrincipal janelaPric, Programa programa){
        this.janela = janela;
        this.rolagem = rolagem;
        this.janelaPric = janelaPric;
        this.programa = programa;
        initComponents();
        janelaPric.incCont();
        periodo = new Periodo(janelaPric.getCont(), this.labelAte);
        programa.getConjPeriodos().add(periodo);
        pronto = true;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        duracao = new javax.swing.JLabel();
        botaoMaisLixo = new javax.swing.JButton();
        nomePeriodo = new javax.swing.JTextField();
        ate = new javax.swing.JLabel();
        campoDuracao = new javax.swing.JFormattedTextField();
        labelAte = new javax.swing.JLabel();

        setBackground(new java.awt.Color(2, 24, 43));
        setPreferredSize(new java.awt.Dimension(950, 40));

        duracao.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        duracao.setForeground(new java.awt.Color(255, 255, 255));
        duracao.setText("Duração:");

        botaoMaisLixo.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        botaoMaisLixo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Figuras/Mais.png"))); // NOI18N
        botaoMaisLixo.setFocusPainted(false);
        botaoMaisLixo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoMaisLixoActionPerformed(evt);
            }
        });

        nomePeriodo.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        nomePeriodo.setForeground(new java.awt.Color(102, 102, 102));
        nomePeriodo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        nomePeriodo.setText("Nome do período");
        nomePeriodo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                nomePeriodoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                nomePeriodoFocusLost(evt);
            }
        });

        ate.setBackground(new java.awt.Color(255, 255, 255));
        ate.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        ate.setForeground(new java.awt.Color(255, 255, 255));
        ate.setText("Até:");

        campoDuracao.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        campoDuracao.setText("00 h 00 m 00 s");
        campoDuracao.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        campoDuracao.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                campoDuracaoCaretUpdate(evt);
            }
        });
        campoDuracao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                campoDuracaoMousePressed(evt);
            }
        });

        labelAte.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        labelAte.setForeground(new java.awt.Color(255, 255, 255));
        labelAte.setText("00 h 00 m 00 s");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(nomePeriodo, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(duracao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(campoDuracao, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ate)
                .addGap(14, 14, 14)
                .addComponent(labelAte)
                .addGap(18, 18, 18)
                .addComponent(botaoMaisLixo)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(duracao)
                    .addComponent(nomePeriodo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ate)
                    .addComponent(campoDuracao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelAte)
                    .addComponent(botaoMaisLixo))
                .addGap(9, 9, 9))
        );

        try{
            MaskFormatter maskID = new MaskFormatter("## h ## m ## s");
            maskID.setPlaceholderCharacter('0');
            maskID.install(campoDuracao);
        }catch(ParseException ex){}
    }// </editor-fold>//GEN-END:initComponents

    private void botaoMaisLixoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoMaisLixoActionPerformed
        if(this.incluido == false){
            ajustaPainel();
            criaPeriodo();
            criaNovoPainel();
            this.incluido = true;
        }else{
        
        }
        
        //Debug
        System.out.println("Tamanho: " + programa.getConjPeriodos().size());
        for(Periodo p : programa.getConjPeriodos()){
            System.out.println(p);
        }
    }//GEN-LAST:event_botaoMaisLixoActionPerformed

    private void campoDuracaoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_campoDuracaoMousePressed
        int posicao = campoDuracao.getCaretPosition();
        if(posicao == 2 || posicao == 3 || posicao == 4){
            campoDuracao.setCaretPosition(5);
        }else if(posicao == 7 || posicao == 8 || posicao == 9|| posicao == 12 || posicao == 13|| posicao == 14){
            campoDuracao.setCaretPosition(10);
        }
    }//GEN-LAST:event_campoDuracaoMousePressed

    private void nomePeriodoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nomePeriodoFocusGained
        if(nomePeriodoUsado == false){
            nomePeriodo.setText("");
            nomePeriodo.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_nomePeriodoFocusGained

    private void nomePeriodoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nomePeriodoFocusLost
        if(nomePeriodo.getText().contentEquals("")){
            nomePeriodo.setText("Nome do Período");
            nomePeriodo.setForeground(new java.awt.Color(102, 102, 102));
            nomePeriodoUsado = false;
        }else{
            nomePeriodoUsado = true;
        }
    }//GEN-LAST:event_nomePeriodoFocusLost

    private void campoDuracaoCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_campoDuracaoCaretUpdate
        long tempo;
        String texto = campoDuracao.getText();
        if(texto.length() == 14 && pronto){
            tempo = Conversor.string2ToLong(texto);
            System.out.println("Segs painel: " + tempo);
            periodo.setDuracao(tempo);
            programa.atualiza(periodo);
        }
    }//GEN-LAST:event_campoDuracaoCaretUpdate

    /**
     *  Ajusta Painel para sua inclusão.
     */
    private void ajustaPainel(){
        if(!this.nomePeriodoUsado){
            this.nomePeriodo.setText("Período " + String.valueOf(janelaPric.getCont()));
            this.nomePeriodo.setForeground(Color.black);
        }
        this.botaoMaisLixo.setIcon(new ImageIcon(getClass().getResource("/Figuras/Lixo.png")));
    }
    
    /**
     *  Cria um objeto Periodo, colocando-o na lista.
     */
    private void criaPeriodo(){
        
    }
    
    /**
    *   Cria um novo painel, ajustando o tamanho da janela.
    */
    private void criaNovoPainel(){
        Painel novoPainel = new Painel(janela, rolagem, janelaPric, programa);
        janela.setPreferredSize(new Dimension(novoPainel.getWidth(),janelaPric.getCont()*(40+(((FlowLayout)janela.getLayout()).getVgap()))));
        janela.setVisible(true);
        janela.add(novoPainel);
        janelaPric.setVisible(true);
        this.rolagem.getVerticalScrollBar().setValue(this.rolagem.getVerticalScrollBar().getMaximum());
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ate;
    private javax.swing.JButton botaoMaisLixo;
    private javax.swing.JFormattedTextField campoDuracao;
    private javax.swing.JLabel duracao;
    public javax.swing.JLabel labelAte;
    private javax.swing.JTextField nomePeriodo;
    // End of variables declaration//GEN-END:variables
}
